sudo: required
services:
- docker
script:
- "/bin/bash script.sh param"
- git -v
env:
  global:
    secure: oFUfOrz35i8vljo07b5aqxrsMHp2zrjTe7mPyxvyAIOhg0tTYKSt/AN+aGkRaeNYJW3D7tndm4AA6J6kgYpwa/Sm+++qLYH62fNulbv5DoQdApE73g7fCLlKIitwfL8cZRguMcRqpTtZXW5mmTmAqtuZizeBRqdIEpTHJVAT2c35YR6w9TXW00S4L6t200ImyS14O3EQhAMPmXL+kORu10pY7Jb3HYxxgttd4wjJhaPJTSs3iDbUuQqgGnfEyt+NPYKOcBx0LCDxDaKI6udK207d4j6yH+w6mOHq4DP7Ke3V+QHnPoF0RC9XFn/lgrnidcT4w/qAfW1l/q2/ehQdekO8qdlOdGAzemzHRc6LT2bh3Y5L4K7Zr1R6yvKALWJS28Pw97M7b7TwVHIq+7Db5PSaC0kid9iSZGZnjtKCix4BwTUhV+8TvJyA6tRTvHTbZFyg3CboQ1Tucf1wBvxQmJGpiaANbDJQHWw28sc9rufpS0sIy92zDNmn0FSTEnNcAHTFsZbv1TyPynBHH8pAa3w1dlvHH1GHQ2owScm20gXyqXurCLjMes6C1SokZAvqqdROdoXBTGg796HTU374ehrPt1AOYwNP7RWbK8yFSPKMoh8TFYC6NXAwtUlsAsfOQYWsTRmEWUDuWVN5rmYMuCXkzks45Ih3zYyrc9QAg3o=
