sudo: required
services:
- docker
before_install:
- echo "doing stuff before installation"
- echo "more stuff"
install:
- echo "installing"
before_script:
- echo "prescript?"
script:
- mkdir test
- pwd
- cd test
- pwd 
- env
