sudo: required
language: node_js
services:
- docker
before_install:
- echo "doing stuff before installation"
- echo "more stuff"
install:
- echo "installing"
before_script:
- echo "prescript?"
script:
- echo "69" > version
- export VERSION=$(cat version)
- echo "version is $VERSION <- version"
- env
- echo "$DB"
branches:
  only:
  - master
env:
  - DB=postgres
