sudo: required
services:
- docker
before_install:
- echo "doing stuff before installation"
- echo "more stuff"
install:
- echo "installing"
before_script:
- prescript?
script:
- "/bin/bash script.sh param"
- git -v
- echo banan > banan && git add banan && git commit -m "banan?" && git push https://jhrv:$MY_TOKEN@github.com/jhrv/travistest
env:
  global:
  - secure: oFUfOrz35i8vljo07b5aqxrsMHp2zrjTe7mPyxvyAIOhg0tTYKSt/AN+aGkRaeNYJW3D7tndm4AA6J6kgYpwa/Sm+++qLYH62fNulbv5DoQdApE73g7fCLlKIitwfL8cZRguMcRqpTtZXW5mmTmAqtuZizeBRqdIEpTHJVAT2c35YR6w9TXW00S4L6t200ImyS14O3EQhAMPmXL+kORu10pY7Jb3HYxxgttd4wjJhaPJTSs3iDbUuQqgGnfEyt+NPYKOcBx0LCDxDaKI6udK207d4j6yH+w6mOHq4DP7Ke3V+QHnPoF0RC9XFn/lgrnidcT4w/qAfW1l/q2/ehQdekO8qdlOdGAzemzHRc6LT2bh3Y5L4K7Zr1R6yvKALWJS28Pw97M7b7TwVHIq+7Db5PSaC0kid9iSZGZnjtKCix4BwTUhV+8TvJyA6tRTvHTbZFyg3CboQ1Tucf1wBvxQmJGpiaANbDJQHWw28sc9rufpS0sIy92zDNmn0FSTEnNcAHTFsZbv1TyPynBHH8pAa3w1dlvHH1GHQ2owScm20gXyqXurCLjMes6C1SokZAvqqdROdoXBTGg796HTU374ehrPt1AOYwNP7RWbK8yFSPKMoh8TFYC6NXAwtUlsAsfOQYWsTRmEWUDuWVN5rmYMuCXkzks45Ih3zYyrc9QAg3o=
  - secure: uKDJvc+uV4JSezwzLAaqeZR+8Eg81OJztb4XFzSfTUtMzkhq4eL+epETYJlpGZRdp/lfBHvyRx+Cii058MoGsLespOPSwi17fHkHhxURsAzY+KJHVvLxgi6VFARfGijcIzo408asWqiQewFeITg73W1AX7rC56dyPYkf2TmM0CVca2wlXf533IwUMd1YoaPQ0wWmsD2DlDM4ih1Tu53MFLpBaggMsQ0YigVd7/l4cV/axspJTfc53GRanMUyK8c6XGj0sfj9UY6OswDD3ELsISvg3Db6S4K9AuUM2tdtcRSi4Mgh9sWMv0X4zHWWgU33FDmaszM4usJSbhkIO72ji1jRYbQwT33AfybiTf37yISmQhgRGPfjeUYvdATrfw0B+JCNRbLZ11dfs9eUN+s5fKISVdPXIXqlnXj3uho64w6SL0l21ZZEgfB2hbrbRjQCv+zNAXhe70fA1FU138ouS6NbllolaOlBFRlMPTrKiQEqrxY3bhlZJ6hdBHgWGx6/IaFliZihl9li69YIwNeuZ4vqHjneNnHyF9FDqDdESR9NoIleIEwF+mSmIy+k4MD7ibz2KXDj1J5AlUBQNHoVajSucNzfnPdIxdAB1lVt9EEi/rZfaXcb+XM89sEjS4l05J6TD9NjNU46K8y6BunKzrpowuZPfJW9p+3fp+0uoCY=
